<?php

/**
 * @file
 */

declare(strict_types=1);

/**
 * @file
 */

use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\webform_test_alter_hooks\Hook\WebformTestAlterHooksHooks;
use Drupal\Core\Form\FormStateInterface;

/* ************************************************************************** */
// Form hooks.
/* ************************************************************************** */

/**
 * Implements hook_form_alter().
 */
#[LegacyHook]
function webform_test_alter_hooks_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  \Drupal::service(WebformTestAlterHooksHooks::class)->formAlter($form, $form_state, $form_id);
}

/**
 * Implements hook_form_webform_submission_form_alter().
 */
#[LegacyHook]
function webform_test_alter_hooks_form_webform_submission_form_alter(array $form, FormStateInterface $form_state, $form_id) {
  \Drupal::service(WebformTestAlterHooksHooks::class)->formWebformSubmissionFormAlter($form, $form_state, $form_id);
}

/**
 * Implements hook_form_webform_submission_BASE_FORM_ID_form_alter().
 *
 * @see webform_form_alter()
 * @see \Drupal\webform\WebformSubmissionForm::getBaseFormId
 * @see \Drupal\Core\Form\FormBuilder::prepareForm
 */
#[LegacyHook]
function webform_test_alter_hooks_form_webform_submission_contact_form_alter(array $form, FormStateInterface $form_state, $form_id) {
  \Drupal::service(WebformTestAlterHooksHooks::class)->formWebformSubmissionContactFormAlter($form, $form_state, $form_id);
}

/**
 * Implements hook_form_webform_submission_FORM_ID_form_alter().
 *
 * @see webform_form_alter()
 * @see \Drupal\webform\WebformSubmissionForm::getFormId
 * @see \Drupal\Core\Form\FormBuilder::prepareForm
 */
#[LegacyHook]
function webform_test_alter_hooks_form_webform_submission_contact_add_form_alter(array $form, FormStateInterface $form_state, $form_id) {
  \Drupal::service(WebformTestAlterHooksHooks::class)->formWebformSubmissionContactAddFormAlter($form, $form_state, $form_id);
}

/**
 * Implements hook_form_webform_submission_FORM_ID_form_alter().
 *
 * @see webform_form_alter()
 * @see \Drupal\webform\WebformSubmissionForm::getFormId
 * @see \Drupal\Core\Form\FormBuilder::prepareForm
 */
#[LegacyHook]
function webform_test_alter_hooks_form_webform_submission_contact_node_1_add_form_alter(array $form, FormStateInterface $form_state, $form_id) {
  \Drupal::service(WebformTestAlterHooksHooks::class)->formWebformSubmissionContactNode1AddFormAlter($form, $form_state, $form_id);
}

/**
 * Implements hook_webform_submission_form_alter().
 *
 * @see \Drupal\webform\WebformSubmissionForm::buildForm
 */
#[LegacyHook]
function webform_test_alter_hooks_webform_submission_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  \Drupal::service(WebformTestAlterHooksHooks::class)->webformSubmissionFormAlter($form, $form_state, $form_id);
}

/* ************************************************************************** */
// Element hooks.
/* ************************************************************************** */

/**
 * Implements hook_webform_element_alter().
 *
 * @see webform.api.php
 * @see \Drupal\webform\WebformSubmissionForm::prepareElements
 */
#[LegacyHook]
function webform_test_alter_hooks_webform_element_alter(array &$element, FormStateInterface $form_state, array $context) {
  \Drupal::service(WebformTestAlterHooksHooks::class)->webformElementAlter($element, $form_state, $context);

}

/**
 * Implements hook_webform_element_ELEMENT_TYPE_alter().
 *
 * @see webform.api.php
 * @see \Drupal\webform\WebformSubmissionForm::prepareElements
 */
#[LegacyHook]
function webform_test_alter_hooks_webform_element_email_alter(array &$element, FormStateInterface $form_state, array $context) {
  \Drupal::service(WebformTestAlterHooksHooks::class)->webformElementEmailAlter($element, $form_state, $context);
}
