<?php

use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\webform_image_select_test\Hook\WebformImageSelectTestHooks;
use Drupal\webform_image_select\Entity\WebformImageSelectImages;

/**
 * Implements hook_webform_image_select_images_WEBFORM_IMAGE_SELECT_IMAGES_ID_alter().
 */
#[LegacyHook]
function webform_image_select_test_webform_image_select_images_animals_alter(array &$images, array &$element) {
  \Drupal::service(WebformImageSelectTestHooks::class)->webformImageSelectImagesAnimalsAlter($images, $element);
}

/**
 * Implements hook_webform_image_select_images_alter().
 */
#[LegacyHook]
function webform_image_select_test_webform_image_select_images_alter(array &$images, array &$element, $id) {
  \Drupal::service(WebformImageSelectTestHooks::class)->webformImageSelectImagesAlter($images, $element, $id);
}
